# Generated by Django 5.0.6 on 2024-06-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=50, unique=True, verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'db_table': 'Director',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50, unique=True, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='Catalogo_Entretenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Titulo')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.tipo')),
            ],
            options={
                'verbose_name': 'Catalogo_entretenimiento',
                'db_table': 'Catalogo_entretenimiento',
            },
        ),
        migrations.CreateModel(
            name='DetallesCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lanzamiento', models.CharField(max_length=50)),
                ('sinopsis', models.TextField()),
                ('temporada', models.IntegerField(blank=True, null=True)),
                ('catalogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Detalles', to='catalogo.catalogo_entretenimiento')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero')),
            ],
            options={
                'verbose_name': 'DetallesCatalogo',
                'db_table': 'DetallesCatalogo',
            },
        ),
    ]
