# Generated by Django 5.0.6 on 2024-07-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_catalogo_entretenimiento_fecha_lanzamiento_and_more'),
        ('usuario', '0003_comentarioforo_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('detalles_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.detallescatalogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historial de Visitas',
                'db_table': 'Historial',
            },
        ),
    ]
