# Generated by Django 5.0.6 on 2024-07-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_historial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
